#!/bin/sh

# Copyright (c) 2018 Lars Kiesow <lkiesow@uos.de>
# https://github.com/lkiesow/automated-quay.io-deployment
# Licensed under the terms of the MIT License.
# See LICENSE for more details.
#
# Modification:
#     Vincent Rouvreau - make it work with github actions
#     cf. https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables

set -ue

payload="{
  \"commit\": \"${GITHUB_SHA}\",
  \"ref\": \"${GITHUB_REF}\",
  \"default_branch\": \"${QUAY_DEFAULT_BRANCH:-master}\"
}"

# Fix webhook URL if necessary
QUAY_WEBHOOK_URL="$(echo "${QUAY_WEBHOOK_URL}" | sed "s_https://:_https://\$token:_")"

curl -H 'Content-Type: application/json' --data "${payload}" "${QUAY_WEBHOOK_URL}"
